/**
 * sync_profiling_data.js — Regenerates data/profiling/* from KPT-Market-Profiling's
 * pipeline output (a sibling repo, ../KPT-Market-Profiling).
 *
 * KPT-Market-Profiling is the data-pipeline repo (Python scripts stay there). This
 * script is the repeatable bridge from its output into this repo's data/profiling/
 * folder — run it any time that pipeline is re-run for an asset (new/updated CSV,
 * taxonomy change). Not a one-shot port: adding a new asset means adding it to
 * ASSETS below and re-running, no other code change required.
 *
 * Run from seasonal-dashboard/ root: node scripts/sync_profiling_data.js
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

// Add asset keys here as their CSVs are cleaned and piped in KPT-Market-Profiling.
// Keys are lowercase (e.g. "gbpusd") and must match that repo's dashboard/data/<key>.js
// filename; the JS const inside is expected to be <KEY_UPPER>_DATA / _PROFILE_EXAMPLES.
const ASSETS = [
  'gbpusd', 'eurusd', 'audusd', 'nzdusd', 'usdcad', 'usdchf', 'usdjpy',
  'xauusd', 'brent', 'wti', 'us500', 'ustech', 'us30', 'btcusd',
];

const SRC_ROOT = path.join(__dirname, '..', '..', 'KPT-Market-Profiling', 'dashboard', 'data');
const OUT_ROOT = path.join(__dirname, '..', 'data', 'profiling');

function loadConst(filePath, constName) {
  const code = fs.readFileSync(filePath, 'utf8');
  const sandbox = {};
  vm.createContext(sandbox);
  vm.runInContext(code + '\n;this.__RESULT__ = ' + constName + ';', sandbox, { filename: filePath });
  if (sandbox.__RESULT__ === undefined) {
    throw new Error('Could not find `' + constName + '` in ' + filePath);
  }
  return sandbox.__RESULT__;
}

function writeGenerated(outPath, lines) {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');
}

function copyDir(srcDir, outDir) {
  fs.mkdirSync(outDir, { recursive: true });
  for (const f of fs.readdirSync(srcDir)) {
    fs.copyFileSync(path.join(srcDir, f), path.join(outDir, f));
  }
}

const meta = {};
let synced = 0, skipped = 0;

for (const asset of ASSETS) {
  const upper = asset.toUpperCase();
  const dataFile = path.join(SRC_ROOT, asset + '.js');

  if (!fs.existsSync(dataFile)) {
    console.log('SKIP (no pipeline output yet):', asset);
    skipped++;
    continue;
  }

  // 1. Stats + profile-summary bundle. Source declares `const <UPPER>_DATA = {...}`,
  //    a lexical binding, not a window property (see KPT-Market-Profiling HANDOVER.md /
  //    market-profiling-system-spec.md §5.2-5.3) — profiling.js resolves the asset key
  //    at runtime from ASSET_CONFIG.id, so it needs a real, dynamically-lookupable
  //    window property here, same fix the source's own calendar loader already applies.
  const data = loadConst(dataFile, upper + '_DATA');
  writeGenerated(path.join(OUT_ROOT, asset + '.js'), [
    '// Auto-generated by scripts/sync_profiling_data.js from KPT-Market-Profiling pipeline output.',
    '// Do not hand-edit — re-run the sync script after the source pipeline output changes.',
    'window.KPT_PROFILING = window.KPT_PROFILING || {};',
    'window.KPT_PROFILING.' + asset + ' = ' + JSON.stringify(data) + ';'
  ]);

  // 2. Profile examples (M15 exemplar candles per profile) — same const-vs-window fix.
  const exFile = path.join(SRC_ROOT, 'profile-examples', asset + '.js');
  if (fs.existsSync(exFile)) {
    const examples = loadConst(exFile, upper + '_PROFILE_EXAMPLES');
    writeGenerated(path.join(OUT_ROOT, 'profile-examples', asset + '.js'), [
      '// Auto-generated by scripts/sync_profiling_data.js from KPT-Market-Profiling pipeline output.',
      '// Do not hand-edit — re-run the sync script after the source pipeline output changes.',
      'window.KPT_PROFILING_EXAMPLES = window.KPT_PROFILING_EXAMPLES || {};',
      'window.KPT_PROFILING_EXAMPLES.' + asset + ' = ' + JSON.stringify(examples) + ';'
    ]);
  }

  // 3. Calendar data — the source pipeline (export_calendar_data.py) already assigns
  //    onto window.KPT_CALENDAR[ASSET][YEAR] / window.KPT_CALENDAR_YEARS[ASSET] (it hit
  //    the same const-vs-window gotcha itself, for a runtime-constructed asset+year
  //    lookup, and fixed it the same way) — copy verbatim, no transform needed.
  const calSrcDir = path.join(SRC_ROOT, 'calendar', asset);
  if (fs.existsSync(calSrcDir)) {
    copyDir(calSrcDir, path.join(OUT_ROOT, 'calendar', asset));
  }

  meta[asset] = { asOf: (data.stats && data.stats.as_of) || null, unit: (data.stats && data.stats.unit) || 'pips' };
  synced++;
  console.log('SYNCED:', asset, '(as of ' + meta[asset].asOf + ')');
}

// Freshness manifest — read by profiling.js to show "data as of ..." honestly,
// mirroring data/signals_manifest.js's SIGNALS_GENERATED pattern.
writeGenerated(path.join(OUT_ROOT, 'manifest.js'), [
  '// Auto-generated by scripts/sync_profiling_data.js — do not hand-edit.',
  'window.KPT_PROFILING_META = ' + JSON.stringify(meta) + ';',
  'const PROFILING_SYNCED = ' + JSON.stringify(new Date().toISOString()) + ';'
]);

console.log('Done. Synced: ' + synced + ', skipped: ' + skipped + '.');
