/**
 * sync_derived_seasonal.js — Bridges KPT-Market-Profiling's statistically-
 * derived seasonal signal (pipeline/gen_seasonal_signal.py's
 * output/<key>_seasonal.json) into data/<id>.js, in the exact bare
 * `const ASSET_CONFIG = {...}; const MONTHS = [...];` format the other 96
 * hand-authored Moore Research asset files use — so the existing
 * js/accordion.js, js/backtest.js etc. render it identically, with zero
 * changes to any shared file.
 *
 * For assets with no Moore Research coverage (crypto, and eventually
 * synthetics — see docs/PLATFORM_ROADMAP.md Tier 6), not a general
 * replacement for the MRC pipeline. See KPT-Market-Profiling's
 * pipeline/gen_seasonal_signal.py for the derivation methodology and why a
 * single ~9-year sample deliberately never reaches 5-star conviction here,
 * and why the 15-YR column reuses the long-term column's computation (a
 * true 15-year window doesn't exist yet for this asset).
 *
 * Also patches data/signals_manifest.js directly (adds/overwrites this
 * asset's 48-entry `com` array) — scripts/gen_signals_manifest.js, the
 * documented generator for that file, isn't present in this repo (see
 * scripts/README.md), so this is the working substitute for the asset(s)
 * this script covers.
 *
 * Run from seasonal-dashboard/ root: node scripts/sync_derived_seasonal.js
 */
const fs = require('fs');
const path = require('path');

// Add an entry here per statistically-derived asset. `key` matches
// KPT-Market-Profiling's output/<key>_seasonal.json; `id` is the
// seasonal-dashboard page/data-file id (assets/{id}.html, data/{id}.js).
const ASSETS = [
  { key: 'btcusd', id: 'btc', name: 'Bitcoin / USD', ltAccent: '#f7931a', tvSymbol: 'COINBASE:BTCUSD' },
];

const SRC_ROOT = path.join(__dirname, '..', '..', 'KPT-Market-Profiling', 'output');
const DATA_DIR = path.join(__dirname, '..', 'data');
const MANIFEST_PATH = path.join(DATA_DIR, 'signals_manifest.js');

function jsStr(s) { return JSON.stringify(s); }

function buildWeekLiteral(w) {
  return `      { wk: ${jsStr(w.wk)}, s5: ${jsStr(w.s5)}, s15: ${jsStr(w.s15)}, s9: ${jsStr(w.s15)}, com: ${jsStr(w.com)}, note: ${jsStr(w.note)} },`;
}

function buildMonthLiteral(mo) {
  const weeks = mo.weeks.map(buildWeekLiteral).join('\n');
  return `  {
    month: ${jsStr(mo.month)}, sig5: ${jsStr(mo.sig5)}, sig15: ${jsStr(mo.sig15)}, sig9: ${jsStr(mo.sig15)},
    combined: ${jsStr(mo.combined)}, combinedLabel: ${jsStr(mo.combinedLabel)}, stars: ${mo.stars},
    note: ${jsStr(mo.note)},
    weeks: [
${weeks}
    ]
  }`;
}

function buildDataFile(asset, seasonal) {
  const ltYears = Math.round(seasonal.elapsed_years);
  const sub = `Seasonal Tendency Analysis · 5-YR · 15-YR · ${ltYears}-YR (statistically derived) · Not Moore Research Center data`;
  const footnote = `Statistically derived from ${seasonal.elapsed_years} years of real ${asset.key.toUpperCase()} price history ` +
    `(${seasonal.first_date} → ${seasonal.as_of}), sourced via TradersWay MT5 export and cleaned by the ` +
    `KPT-Market-Profiling pipeline. Moore Research Center does not cover crypto — this signal uses the site's own ` +
    `Raw Price Tendency methodology (js/backtest.js) instead of hand-authored chart analysis. The 15-YR column shows ` +
    `the same full-history computation as the ${ltYears}-YR column, since that much price history does not exist yet. ` +
    `Star conviction is capped below the site's usual maximum for this reason — see the page's derived-note box.`;

  const monthsLiteral = seasonal.months.map(buildMonthLiteral).join(',\n');

  return `// data/${asset.id}.js — Auto-generated by scripts/sync_derived_seasonal.js from
// KPT-Market-Profiling's pipeline/gen_seasonal_signal.py output. Do not hand-edit —
// re-run both scripts after the source price history is refreshed.
// Statistically derived, NOT Moore Research Center data — see ASSET_CONFIG.footnote.

const ASSET_CONFIG = {
  id:       ${jsStr(asset.id)},
  name:     ${jsStr(asset.name)},
  sub:      ${jsStr(sub)},
  footnote: ${jsStr(footnote)},
  ltLabel:  ${jsStr(ltYears + '-YR')},
  ltSigKey: "sig9",
  ltKey:    "s9",
  ltAccent: ${jsStr(asset.ltAccent)},
  tvSymbol: ${jsStr(asset.tvSymbol)},
};

const MONTHS = [
${monthsLiteral}
];
`;
}

// Surgical text patch, not a full-object rebuild — signals_manifest.js's 96
// existing Moore Research entries must stay byte-identical (same formatting,
// same line-wrapping) since scripts/gen_signals_manifest.js (the real
// generator for those) isn't present in this repo to re-diff against, and a
// full rewrite would otherwise reformat every unrelated asset's entry too.
function patchSignalsManifest(asset, seasonal) {
  const flat = [];
  seasonal.months.forEach((mo) => mo.weeks.forEach((w) => flat.push(w.com)));
  // Match backtest.js/accordion.js's own 4-per-line convention for readability.
  const rows = [];
  for (let i = 0; i < flat.length; i += 4) {
    rows.push('    ' + flat.slice(i, i + 4).map(jsStr).join(', ') + (i + 4 < flat.length ? ',' : ''));
  }
  const entryBlock = `  ${jsStr(asset.id)}: [\n${rows.join('\n')}\n  ]`;

  let code = fs.readFileSync(MANIFEST_PATH, 'utf8');
  // Anchor on the asset's own (unique) key name, not "the last entry in the
  // file" — a lazy regex spanning the whole object body is ambiguous about
  // where it starts/stops when there are 96+ candidate entries.
  const keyPattern = new RegExp(`\\n  ${JSON.stringify(asset.id)}: \\[[\\s\\S]*?\\n  \\](,?)`, 'm');
  if (keyPattern.test(code)) {
    // Existing key for this asset — replace in place, preserve its trailing comma.
    code = code.replace(keyPattern, (_, comma) => `\n${entryBlock}${comma}`);
  } else {
    // New key — insert right before the object's one-and-only closing `};`,
    // adding a comma after whatever the previous last entry was if it
    // doesn't already have one.
    const closeIdx = code.lastIndexOf('\n};');
    if (closeIdx === -1) {
      throw new Error('could not find the closing `};` in ' + MANIFEST_PATH);
    }
    let before = code.slice(0, closeIdx);
    if (!/,\s*$/.test(before)) before += ',';
    code = before + '\n' + entryBlock + code.slice(closeIdx);
  }

  const generated = new Date().toISOString();
  code = code.replace(/const SIGNALS_GENERATED = '[^']*';/, `const SIGNALS_GENERATED = '${generated}';`);
  code = code.replace(/^\/\/ Generated: .*$/m, `// Generated: ${generated}`);

  fs.writeFileSync(MANIFEST_PATH, code, 'utf8');
}

for (const asset of ASSETS) {
  const srcPath = path.join(SRC_ROOT, `${asset.key}_seasonal.json`);
  if (!fs.existsSync(srcPath)) {
    console.log('SKIP (no seasonal output yet):', asset.key);
    continue;
  }
  const seasonal = JSON.parse(fs.readFileSync(srcPath, 'utf8'));

  const outPath = path.join(DATA_DIR, `${asset.id}.js`);
  fs.writeFileSync(outPath, buildDataFile(asset, seasonal), 'utf8');
  console.log('WROTE:', outPath, `(${seasonal.year_range}, ${seasonal.elapsed_years}y elapsed)`);

  patchSignalsManifest(asset, seasonal);
  console.log('PATCHED:', MANIFEST_PATH, `(key "${asset.id}")`);
}
